### ISSUE TITLE
코딩테스트 대비 스터디 방식 제안

### ISSUE THREAD

**Issue by kimmincheol-kor** [pangpang-study/algorithm-coding-test-study#1]
@hanuk96 @hydenny @Akgop @YuHyeonGeun-KOR

### 스터디의 목적
1. 코딩 테스트를 함께 준비하는 목적은 `내가 모르는 것을 공유하고 질문`하여 해답을 얻는다.
2. `남이 모르는 것`에 대해 생각해보며 내 생각 공유 및 토론하며 한단계 더 성장한다.
3. 문제를 잘 푸는 동료를 보면서 목표가 생기고 `동기부여`를 얻는다.

### 제안하는 나의 개인적인 생각
1. 코딩 테스트 문제를 많이 푸는건 내가 스스로 결정, 제어가 가능
2. 어려운 문제를 풀어나가는건 모두가 함께 하기에 어려울 수 있음
3. 모임에서는 함께 다룰 수 있는 문제로, 누군가 모르거나 고민하는 것에 대해 토론하는게 효과적임
4. 코딩 테스트는 문제를 풀 수 있는지 뿐만 아니라, 시간 내에 푸는 것이 중요

### 스터디 방식
1. 매주 모이는 시간에 문제 하나를 정해서 동시에 풀기 시작한다
`알고리즘을 아느냐의 문제가 아닌, 시간 내에 구현을 할 수 있느냐가 중요하기 때문에 "구현" 문제를 추천한다`
2. 다 풀면 디스코드에 솔 완료. 화면을 캡처해서 올린다
3. 1등부터 5등까지 정해진다
4. 1등, 3등, 5등이 일주일 동안 풀 문제를 하나씩 정한다 (총 3문제)
`본인이 해당 문제를 통해 배울점이 명확한 문제가 좋다 = 다른 사람에게 질문할 수 있는`
5. 3문제는 일주일동안 풀고, 풀이 방법도 정리한다. (손 필기가 아닌 Markdown 으로 작성 -> 블로그에 옮기기도 좋음)
6. `algorithm-coding-test-study` 레포에 PR을 올린다.
```
프로젝트 구조는 본인 닉네임으로 폴더가 하나씩 존재 -> 총 5개의 폴더
매주 공통 branch를 생성 -> "210930-study"

본인 branch 생성 -> "210930-kmc"
본인 닉네임의 폴더에 날짜 폴더 생성 -> "210930"
정해진 3문제는 1,2,3 번 문제로 칭함 (ex. 1.py, 2.py, 3.py)

문제 3개 풀고, PR 본문에 풀이과정 작성 -> pull request "210930-kmc" to "210930-study"
다른 사람들은 해당 PR 을 보고 최소 1개 이상의 리뷰 작성 (다른 사람의 코드를 보는 능력을 기르기 위함)
```

### 결과
1. 일주일에 3문제를 함께 푼다
2. 3문제에 대해 모두의 코드를 보고, 모두의 코드에 리뷰를 남긴다 -> 내 코드에 대한 성장, 남의 코드를 보는 능력 성장
3. 매주 문제를 동시에 풀고 순위를 확인하며 시간 내에 문제를 푸는 연습
4. 마크다운 문법 익히기 및 git 사용하는 연습

**Comment by Akgop** [comment]
오 재밌을거같음

**Comment by kimmincheol-kor** [comment]
함께 디스코드하는 시간에는 `시간 내의 문제풀기` 정도만 하는거고,
해당 문제에 대한 질문이나 토론 정도 나누면 될 것 같음

추가로 `CS 공부`까지 스터디로 하자는 의견이 생긴다면,
우테코 수준 정도로 주 1회 1명 정해서 10분정도 정리해서 발표하는 방법도
공부 -> 정리 -> 말하기 능력까지 성장 가능할듯

**Comment by hydenny** [comment]
괜찮을듯합니다~~
